(in-package :game)

(defun blocks-sprite-sheet-class-test ()
  (sdl:with-init ()
    (sdl:window 300 300)
    (setf (sdl:frame-rate) 60)
    (let ((ins (make-instance 'blocks-sprite-sheet)))      
      (print (sprite-cells2 40 40 "blocks1" (cells ins)))
      (print (gethash "blocks1" (sprite-sheet ins)))
      (sdl:with-events (:poll)
	(:quit-event () t)
	(:key-down-event  (:key key)
			  (when (sdl:key= key :sdl-key-escape)
			    (sdl:push-quit-event)))
	(:idle ()
	       (sdl:clear-display sdl:*black*)
	       (sdl:draw-surface-at-* (gethash "blocks1" (sprite-sheet ins)) 0 0 :cell 1)
	       (sdl:update-display))))))
  
(blocks-sprite-sheet-class-test)
