(in-package :game)

(defun player-draw-class-test ()
  (sdl:with-init ()
    (sdl:window 300 300)
    (setf (sdl:frame-rate) 60)
    (let ((ins (make-instance 'player-draw)))
      (print ins)
      (setf (action-flag *player-flag*) "running-right")
      (sdl:with-events (:poll)
	(:quit-event () t)
	(:key-down-event  (:key key)
			  (when (sdl:key= key :sdl-key-escape)
			    (sdl:push-quit-event)))
	(:idle ()
	       (sdl:clear-display sdl:*black*)
	       (draw-sprite ins 0 0)
	       (sdl:update-display))))))

(player-draw-class-test)
